services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cinetrack-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    secrets:
      - db_connection_string
      - rabbitmq_connection_string
      - redis_connection_string
      - tmdb_api_key
      - smtp_password
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - cinetrack-net

  postgres:
    image: postgres:17-alpine
    container_name: cinetrack-postgres
    environment:
      POSTGRES_DB: cinetrack
      POSTGRES_USER: cinetrack
      POSTGRES_PASSWORD: cinetrack_secret
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cinetrack -d cinetrack"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cinetrack-net

  redis:
    image: redis:7-alpine
    container_name: cinetrack-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cinetrack-net

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: cinetrack-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: cinetrack
      RABBITMQ_DEFAULT_PASS: cinetrack_secret
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - cinetrack-net

secrets:
  db_connection_string:
    file: ./secrets/db_connection_string
  rabbitmq_connection_string:
    file: ./secrets/rabbitmq_connection_string
  redis_connection_string:
    file: ./secrets/redis_connection_string
  tmdb_api_key:
    file: ./secrets/tmdb_api_key
  smtp_password:
    file: ./secrets/smtp_password

volumes:
  postgres-data:
  redis-data:
  rabbitmq-data:

networks:
  cinetrack-net:
    driver: bridge
